
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_TOTES_SUCCESS = 'GET_TOTES_SUCCESS';

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS';
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS';
export const GET_SURVEY_QUESTION_SUCCESS = 'GET_SURVEY_QUESTION_SUCCESS';
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_ORDER_HISTORY = 'SET_ORDER_HISTORY';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const SET_PAYMENT_METHODS = 'SET_PAYMENT_METHODS';
export const GET_ANSWERED_QUESTIONS = 'GET_ANSWERED_QUESTIONS';